ALTER TABLE features_daily
    ADD COLUMN IF NOT EXISTS rsi_14 NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS macd_line NUMERIC(12, 6),
    ADD COLUMN IF NOT EXISTS macd_signal NUMERIC(12, 6),
    ADD COLUMN IF NOT EXISTS macd_histogram NUMERIC(12, 6),
    ADD COLUMN IF NOT EXISTS atr_14 NUMERIC(10, 6),
    ADD COLUMN IF NOT EXISTS bb_upper NUMERIC(12, 6),
    ADD COLUMN IF NOT EXISTS bb_middle NUMERIC(12, 6),
    ADD COLUMN IF NOT EXISTS bb_lower NUMERIC(12, 6);
